name: ESP-IDF Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install ESP-IDF
      run: |
        git clone --recursive -b v5.2.2 https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh
        . ./export.sh

    - name: Install IDF Component Manager and dependencies
      run: |
        . ./esp-idf/export.sh
        python -m pip install idf-component-manager
        idf.py reconfigure

    - name: Build
      id: build
      run: |
        . ./esp-idf/export.sh
        idf.py build

    - name: Create Tag and Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a ${{ steps.build.outputs.version }} -m "Version ${{ steps.build.outputs.version }}"
        git push --tags

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        name: "${{ steps.build.outputs.version }}"
        files: |
          output/ZigUSB_C6.ota
          output/ZigUSB_C6.bin
          