name: ESP-IDF Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install ESP-IDF
      run: |
        git clone --recursive -b v5.2.2 https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh
        . ./export.sh

    - name: Install IDF Component Manager and dependencies
      run: |
        . ./esp-idf/export.sh
        python -m pip install idf-component-manager
        idf.py reconfigure

    - name: Build
      run: |
        . ./esp-idf/export.sh
        idf.py build

    - name: Archive build output artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          output/ZigUSB_C6.ota
          output/ZigUSB_C6.bin