name: ESP-IDF Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/idf:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            idf.py build
