name: ESP-IDF Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install ESP-IDF and Build project
        uses: rmshub/esp-idf-action@v5
        with: 
            esp_idf_version: v5.2.2
            esp_idf_target: esp32c6

      - name: Archive build output artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: |
            output/ZigUSB_C6.ota
            output/ZigUSB_C6.bin